### ISSUE TITLE
[Linux] GDevelop freezes upon opening a scene

### ISSUE THREAD

**Issue by Wend1go** [4ian/GD#338]
The current trunk version of GD freezes the IDE upon opening an existing or creating a new scene.
Confirmed on multiple systems with AMD and Nvidia GPUs.

Details (and error output in YT-video) under:
http://compilgames.net/forum/viewtopic.php?f=20&t=8770

**Comment by victorlevasseur** [comment]
Can you launch it with gdb ? and instead of typing ```r``` or ```run```, type ```run --sync``` and then ```bt``` after the crash.

**Comment by Marc34** [comment]
Bool attribute "folderProject" not found, returning 0Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Bool attribute "updateIfNotVisible" not found, returning 1Child effects not found in SerializerElement::GetChild
Child effects not found in SerializerElement::GetChild
The program 'GDIDE' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
(Details: serial 161 error_code 10 request_code 2 minor_code 0)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by victorlevasseur** [comment]
The bug is probably caused by the SFML window embedded in the wxWidgets GUI (which has always been a kind of kack). I'm gonna try to do the SFML rendering offscreen and use a wxWidgets window to display the result. But it needs a lot of work to change this. I'll post further information when I'll have some code to test (as I can't test myself).

**Comment by Wend1go** [comment]
Tried to run the IDE with "run --sync" but it still freezes without letting me enter further commands in the console.
This is the last output I get before the freeze:

```(GDIDE:2991): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed
[Thread 0x7fffdf7fe700 (LWP 2998) exited]
[New Thread 0x7fffdf7fe700 (LWP 3055)]
[New Thread 0x7fff3e193700 (LWP 3056)]
[New Thread 0x7fff3d992700 (LWP 3057)]
[Thread 0x7fff3e193700 (LWP 3056) exited]
[Thread 0x7fff3d992700 (LWP 3057) exited]
[New Thread 0x7fff3d992700 (LWP 3059)]
[Thread 0x7fffdf7fe700 (LWP 3055) exited]
[New Thread 0x7fffdf7fe700 (LWP 3060)]
[New Thread 0x7fff3e193700 (LWP 3061)]
[New Thread 0x7fff3d191700 (LWP 3062)]
[Thread 0x7fffdf7fe700 (LWP 3060) exited]
[Thread 0x7fff3d191700 (LWP 3062) exited]
[Thread 0x7fff3e193700 (LWP 3061) exited]
[New Thread 0x7fff3e193700 (LWP 3063)]
[Thread 0x7fff3e193700 (LWP 3063) exited]
[New Thread 0x7fff3e193700 (LWP 3064)]
[Thread 0x7fff3d992700 (LWP 3059) exited]
[New Thread 0x7fff3d992700 (LWP 3065)]
[Thread 0x7fff3e193700 (LWP 3064) exited]
[New Thread 0x7fff3e193700 (LWP 3066)]
[Thread 0x7fff3d992700 (LWP 3065) exited]
[New Thread 0x7fff3d992700 (LWP 3067)]
[Thread 0x7fff3d992700 (LWP 3067) exited]
Sending analytics data...done (201)
The program 'GDIDE' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 160 error_code 10 request_code 2 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by victorlevasseur** [comment]
**Can you try the bugfix/sfml-offscreen branch of my fork of GDevelop ?**

It contains a new way to embed SFML into a wxWidgets GUI: basically, the rendering is done offscreen (on a texture) that is then downloaded from the GPU and drawn with wxWidgets (with the CPU) in the GUI. The performances are obviously lower than with direct SFML drawing but it avoids the bug (for compiled games, only SFML is used, as before, so no worries for the performances for compiled games).

**The keyboard and the mouse don't act in *scene previews* in this branch, however, the game/layout editor should work normally.**

**Comment by Wend1go** [comment]
Your offscreen-branch runs without errors/freezing.
But as you said placement of the objects in the scene is a little choppy.

**Comment by victorlevasseur** [comment]
Can you try again with the lastest commit I pushed? This gives a great improvement to the rendering performances in the GDevelop IDE.

**Comment by 4ian** [comment]
Awesome work Victor, let me know when it's working good on Linux and Windows so I can test it on OS X :)

**Comment by victorlevasseur** [comment]
Ok, this will probably fix the yield freeze on Mac OS X too

Le mar. 24 janv. 2017 23:30, Florian Rival <notifications@github.com> a
écrit :

**Comment by Wend1go** [comment]
Works great, I don't recognize any difference in performance.
Tested the build with a more complex project of mine.

But it throws a Memory access violation in line 11 when I close the IDE.
`./StartGDevelop.sh: Zeile 11:  3320 Speicherzugriffsfehler  GDK_BACKEND=x11 ./GDIDE`
Don't know it if matters.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff31cd404 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007ffff31cd404 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fffe914c82c in ?? () from /usr/lib/nvidia-367/libGLX_nvidia.so.0
#2  0x00007fffe9123d28 in ?? () from /usr/lib/nvidia-367/libGLX_nvidia.so.0
#3  0x00007fffeeb104ce in ?? () from /usr/lib/nvidia-367/libGLX.so.0
#4  0x00007ffff6cfd15c in ?? () from libsfml-window.so.2.4
#5  0x00007ffff6cef891 in ?? () from libsfml-window.so.2.4
#6  0x00007ffff6cf11f5 in sf::GlResource::TransientContextLock::TransientContextLock() () from libsfml-window.so.2.4
#7  0x00007ffff6f424cd in sf::Texture::~Texture() () from libsfml-graphics.so.2.4
#8  0x00007ffff38c553a in __cxa_finalize () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007ffff71dfc33 in ?? () from libGDCpp.so
#10 0x00007fffffffdd40 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by 4ian** [comment]
@victorlevasseur What is the state of your branch to change the rendering? Can I help? 😃

**Comment by victorlevasseur** [comment]
See #340 for more detail about the progress.

**Comment by dos1** [comment]
Merging in #340 fixes the issue for me.

**Comment by Translator5** [comment]
For me using git-version 20180125-1 causes same freeze on opening of a szene :disappointed:

**Comment by PawBud** [comment]
This issue is also outdated & resolved @4ian and hence should be closed.
