### ISSUE TITLE
newIDE - unable to launch preview

### ISSUE THREAD

**Issue by blurymind** [4ian/GD#402]
Previewing seems to have stopped working for me. I get this in console btw

```
D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-error-overlay\lib\effects\proxyConsole.js:56 Can't upload all objects: Error: Missing credentials in config
    at credError (http://localhost:3000/static/js/bundle.js:108993:40)
    at Config.getCredentials (http://localhost:3000/static/js/bundle.js:109034:14)
    at Request.VALIDATE_CREDENTIALS (http://localhost:3000/static/js/bundle.js:110040:26)
    at Request.callListeners (http://localhost:3000/static/js/bundle.js:62630:18)
    at Request.emit (http://localhost:3000/static/js/bundle.js:62606:10)
    at Request.emit (http://localhost:3000/static/js/bundle.js:111787:14)
    at Request.transition (http://localhost:3000/static/js/bundle.js:111126:10)
    at AcceptorStateMachine.runTo (http://localhost:3000/static/js/bundle.js:115537:12)
    at Request.runTo (http://localhost:3000/static/js/bundle.js:111507:15)
    at Request.send (http://localhost:3000/static/js/bundle.js:111471:10)
    at features.constructor.makeRequest (http://localhost:3000/static/js/bundle.js:113262:27)
    at features.constructor.svc.(anonymous function) [as putObject] (http://localhost:3000/static/js/bundle.js:113568:23)
    at http://localhost:3000/static/js/bundle.js:205567:25
    at new Promise (<anonymous>)
    at BrowserS3FileSystem._uploadObject (http://localhost:3000/static/js/bundle.js:205566:12)
    at Array.map (<anonymous>)
    at BrowserS3FileSystem.uploadPendingObjects (http://localhost:3000/static/js/bundle.js:205556:52)
    at http://localhost:3000/static/js/bundle.js:205858:32
    at <anonymous>
__stack_frame_overlay_proxy_console__ @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-error-overlay\lib\effects\proxyConsole.js:56
(anonymous) @ D:\BACKUP\asus\GD-master\newIDE\app\src\Export\BrowserS3FileSystem.js:26
Promise rejected (async)
BrowserS3FileSystem.uploadPendingObjects @ D:\BACKUP\asus\GD-master\newIDE\app\src\Export\BrowserS3FileSystem.js:22
(anonymous) @ D:\BACKUP\asus\GD-master\newIDE\app\src\Export\BrowserS3PreviewLauncher.js:84
Promise resolved (async)
BrowserS3PreviewLauncher.launchLayoutPreview @ D:\BACKUP\asus\GD-master\newIDE\app\src\Export\BrowserS3PreviewLauncher.js:77
(anonymous) @ D:\BACKUP\asus\GD-master\newIDE\app\src\MainFrame\index.js:279
watchPromiseInState @ D:\BACKUP\asus\GD-master\newIDE\app\src\Utils\WatchPromiseInState.js:12
MainFrame._this._launchLayoutPreview @ D:\BACKUP\asus\GD-master\newIDE\app\src\MainFrame\index.js:278
onPreview @ D:\BACKUP\asus\GD-master\newIDE\app\src\MainFrame\Editors\EventsEditor.js:42
EnhancedButton._this.handleClick @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\material-ui\internal\EnhancedButton.js:144
ReactErrorUtils.invokeGuardedCallback @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactErrorUtils.js:70
executeDispatch @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\EventPluginUtils.js:85
executeDispatchesInOrder @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\EventPluginUtils.js:108
executeDispatchesAndRelease @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\EventPluginHub.js:54
forEachAccumulated @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\forEachAccumulated.js:24
processEventQueue @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\EventPluginHub.js:257
runEventQueueInBatch @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactEventEmitterMixin.js:17
handleTopLevel @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactEventEmitterMixin.js:28
handleTopLevelImpl @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactEventListener.js:72
perform @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\Transaction.js:140
batchedUpdates @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactDefaultBatchingStrategy.js:62
batchedUpdates @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactUpdates.js:97
dispatchEvent @ D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-dom\lib\ReactEventListener.js:147
D:\BACKUP\asus\GD-master\newIDE\app\node_modules\react-error-overlay\lib\effects\proxyConsole.js:56 Unable to launch the preview! raw error: Error: Missing credentials in config
    at credError (http://localhost:3000/static/js/bundle.js:108993:40)
    at Config.getCredentials (http://localhost:3000/static/js/bundle.js:109034:14)
    at Request.VALIDATE_CREDENTIALS (http://localhost:3000/static/js/bundle.js:110040:26)
    at Request.callListeners (http://localhost:3000/static/js/bundle.js:62630:18)
    at Request.emit (http://localhost:3000/static/js/bundle.js:62606:10)
    at Request.emit (http://localhost:3000/static/js/bundle.js:111787:14)
    at Request.transition (http://localhost:3000/static/js/bundle.js:111126:10)
    at AcceptorStateMachine.runTo (http://localhost:3000/static/js/bundle.js:115537:12)
    at Request.runTo (http://localhost:3000/static/js/bundle.js:111507:15)
    at Request.send (http://localhost:3000/static/js/bundle.js:111471:10)
    at features.constructor.makeRequest (http://localhost:3000/static/js/bundle.js:113262:27)
    at features.constructor.svc.(anonymous function) [as putObject] (http://localhost:3000/static/js/bundle.js:113568:23)
    at http://localhost:3000/static/js/bundle.js:205567:25
    at new Promise (<anonymous>)
    at BrowserS3FileSystem._uploadObject (http://localhost:3000/static/js/bundle.js:205566:12)
    at Array.map (<anonymous>)
    at BrowserS3FileSystem.uploadPendingObjects (http://localhost:3000/static/js/bundle.js:205556:52)
    at http://localhost:3000/static/js/bundle.js:205858:32
    at <anonymous>
```
I am on the latest version of nodejs 8.7.0

seems to be a security thing

**Comment by 4ian** [comment]
This is because you're running GDevelop in the browser, which does not have any file system access, so preview are generated and temporarily stored on a Amazon S3 bucket.
There is an environment file called `.env.dist` that you can rename in `.env.local` to set the credentials of the Amazon S3 bucket to use (but the address of the S3 bucket is hardcoded for now in [BrowserS3PreviewLauncher.js](https://github.com/4ian/GD/blob/a291d846d862102f3fb7af709a9760be03555392/newIDE/app/src/Export/BrowserS3PreviewLauncher.js#L14) - you can submit a PR to set it in the .env file if you wish!)

As long as the correct credentials and adresses are not set, the preview won't work. Amazon rules do not allow sharing these credentials for security reasons.

You can also just launch GDevelop in Electron, so that GDevelop has access to file system and generate previews 100% locally: https://github.com/4ian/GD/blob/master/newIDE/README.md#development-of-the-standalone-app 😄

**Comment by blurymind** [comment]
Thank you for explaining this

I will look into it when I get home :)

**Comment by 4ian** [comment]
Ok let me know if you have any problem launching GD with Electron

**Comment by 4ian** [comment]
Closing this as it should be fixed and not relevant anymore :)
