### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by luigi1610** [4ian/GD#440]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
TypeError: layout.getAllBehaviorSharedDataNames is not a function
    at ScenePropertiesDialog.render (http://localhost:3000/static/js/bundle.js:264152:47)
    at finishClassComponent (http://localhost:3000/static/js/bundle.js:178469:31)
    at updateClassComponent (http://localhost:3000/static/js/bundle.js:178446:12)
    at beginWork (http://localhost:3000/static/js/bundle.js:178821:16)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:180820:16)
    at workLoop (http://localhost:3000/static/js/bundle.js:180884:26)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:171138:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:171177:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:171034:27)
    at renderRoot (http://localhost:3000/static/js/bundle.js:180962:7)
    at performWorkOnRoot (http://localhost:3000/static/js/bundle.js:181610:24)
    at performWork (http://localhost:3000/static/js/bundle.js:181563:7)
    at requestWork (http://localhost:3000/static/js/bundle.js:181474:7)
    at scheduleWorkImpl (http://localhost:3000/static/js/bundle.js:181328:11)
    at scheduleWork (http://localhost:3000/static/js/bundle.js:181285:12)
    at Object.enqueueSetState (http://localhost:3000/static/js/bundle.js:176808:7)
    at MainFrame../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/bundle.js:213266:16)
    at http://localhost:3000/static/js/bundle.js:249056:15
    at MainFrame._this.closeProject (http://localhost:3000/static/js/bundle.js:249082:47)
    at MainFrame._this.loadFromProject (http://localhost:3000/static/js/bundle.js:249055:13)
    at http://localhost:3000/static/js/bundle.js:249049:24
    at MainFrame._this.closeProject (http://localhost:3000/static/js/bundle.js:249082:47)
    at http://localhost:3000/static/js/bundle.js:249048:15
    at timeFunction (http://localhost:3000/static/js/bundle.js:271154:3)
    at MainFrame._this.loadFromSerializedProject (http://localhost:3000/static/js/bundle.js:249044:89)
    at http://localhost:3000/static/js/bundle.js:249066:19
```

## Component stack (don't write anything here)
```

    in ScenePropertiesDialog (at index.js:683)
    in div (at index.js:574)
    in InstancesFullEditor (at SceneEditor.js:37)
    in SceneEditor (at index.js:452)
    in ErrorBoundary (at ErrorBoundary.js:80)
    in ErrorBoundary (at index.js:876)
    in div (at index.js:875)
    in div (created by TabTemplate)
    in TabTemplate (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (at Tabs.js:38)
    in ThemableTabs (created by MuiComponent)
    in MuiComponent (at index.js:861)
    in div (at index.js:814)
    in I18nextProvider (at Providers.js:26)
    in MuiThemeProvider (at Providers.js:25)
    in DragDropContextProvider (created by DragDropContext(DragDropContextProvider))
    in DragDropContext(DragDropContextProvider) (at Providers.js:24)
    in Providers (at index.js:813)
    in MainFrame (at index.js:83)
```

**Comment by 4ian** [comment]
Have you cloned and compiled GD by yourself or used a version downloaded from the website/Github?

**Comment by 4ian** [comment]
If you're launching GDevelop by yourself, please remove newIDE/app/public/libGD.js and launch again `yarn start` or `npm run start` :)

**Comment by 4ian** [comment]
Closing this as it should not be a problem anymore
