### ISSUE TITLE
Crash while using an editor

### ISSUE THREAD

**Issue by benjamindalgas** [4ian/GD#461]
=> Please write here a short description of when the error occured and how to reproduce it.
You also may have to create an account on GitHub before posting.

When you're ready, click on "Submit new issue". Don't change the rest of the message. Thanks!

## Error stack (don't write anything here)
```
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at r.determineFontProperties (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2089237)
    at r.updateText (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2086021)
    at r.get (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2084403)
    at r.getDefaultWidth (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2195072)
    at e.getInstanceWidth (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2223069)
    at e.value (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2224947)
    at InitialInstanceJSFunctor.instancesRenderer.invoke (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2224703)
    at Array.<anonymous> (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:20:26536)
    at _emscripten_asm_const_iii (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:20:32013)
    at Array.eA (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:24:181130)
    at Array.dA (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:24:181088)
    at nX (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:26:76464)
    at Yq (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:24:94611)
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/libGD.js:5207:3)
    at e.value (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2225387)
    at e.value (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2221372)
    at t.e._renderScene (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2206700)
    at t.e.restartSceneRendering (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2207099)
    at t.value (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2213517)
    at updateClassInstance (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:981932)
    at beginWork (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:991395)
    at o (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:1003529)
    at a (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:1003850)
    at s (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:1004088)
    at w (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:1007632)
    at _ (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:1007369)
    at batchedUpdates (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:1008798)
    at Z (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:968796)
    at Me (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:973256)
    at HTMLDocument.r (file:///C:/Users/Dalgas%20Family/AppData/Local/Programs/gdevelop/resources/app.asar/www/static/js/main.e887aa72.js:1:2612930)
```

## Component stack (don't write anything here)
```

    in t
    in div
    in n
    in div
    in t
    in s
    in div
    in div
    in t
    in div
    in t
    in g
    in t
    in t
    in div
    in t
    in t
    in t
    in v
    in div
    in div
    in c
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in t
    in t
    in t
    in t
    in DragDropContext(t)
    in t
    in t
    in t
```

**Comment by 4ian** [comment]
I'm closing this as we don't have any more details for now!
