### ISSUE TITLE
Unhandled 'error' event when running npm start in /newIDE/app

### ISSUE THREAD

**Issue by RyanNerd** [4ian/GD#467]
System: Linux Mint 18.2 64 -bit
I thought it may have just been `node_modules` corruption but I destroyed that directory and did an `npm install` to rebuild; followed by `npm start`

Error vomit:
```
Starting the development server...

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/ryan/Fork/GD/newIDE/app/public/res/actions/rectangle.png ENOSPC
    at FSWatcher.start (fs.js:1402:19)
    at Object.fs.watch (fs.js:1428:11)
    at createFsWatchInstance (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:171:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/index.js:257:10)
    at createFsWatchInstance (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/ryan/Fork/GD/newIDE/app/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:171:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdevelop-ide@0.1.0 start: `npm run import-resources && react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdevelop-ide@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ryan/.npm/_logs/2018-04-13T21_50_49_109Z-debug.log
```

**Comment by 4ian** [comment]
Looks like your system does not have enough watchers to watch the changes that can be made in the source file.
I would suggest to try these solutions: https://stackoverflow.com/questions/22475849/node-js-error-enospc

Maybe we can add a line in the README if it proves to be useful :) Let me know!

**Comment by RyanNerd** [comment]
Thanks for your quick response. I just followed the directions in the link you gave me and it appears to be working now!
I'll create a PR to update the README

**Comment by 4ian** [comment]
Great! Thanks! 😄

**Comment by Daniel0liver** [comment]
amazing,  thank you ;)
