### ISSUE TITLE
Segfault when previewing a second time a game with the physic automatism

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#77]
The backtrace : 
```
Unloaded compiled code0x32f1af0
Launching GD C++ Platform preview...
Scene Editor canvas reloading... ( Step 1/2 )
Switching to preview mode...
Scene canvas reloading... ( Step 2/2 )
Disabling tasks related to scene:New scene
Initializing RuntimeScene from layout...

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd118b387 in b2World::DestroyBody(b2Body*) ()
   from ./CppPlatform/Extensions//PhysicsAutomatism.xgdle
(gdb) bt
#0  0x00007fffd118b387 in b2World::DestroyBody(b2Body*) ()
   from ./CppPlatform/Extensions//PhysicsAutomatism.xgdle
#1  0x00007fffd115c9e8 in PhysicsAutomatism::~PhysicsAutomatism() ()
   from ./CppPlatform/Extensions//PhysicsAutomatism.xgdle
#2  0x00007fffd115ca49 in PhysicsAutomatism::~PhysicsAutomatism() ()
   from ./CppPlatform/Extensions//PhysicsAutomatism.xgdle
#3  0x00007ffff725c6df in RuntimeObject::~RuntimeObject() () from ./libGDCpp.so
#4  0x00007fffd0ead817 in RuntimeTextObject::~RuntimeTextObject() ()
   from ./CppPlatform/Extensions//TextObject.xgdle
#5  0x00007ffff727f2f8 in std::vector<boost::shared_ptr<RuntimeObject>, std::allocator<boost::shared_ptr<RuntimeObject> > >::~vector() () from ./libGDCpp.so
#6  0x00007ffff727f453 in ObjInstancesHolder::Clear() () from ./libGDCpp.so
#7  0x00007ffff727d390 in RuntimeScene::LoadFromSceneAndCustomInstances(gd::Layout const&, gd::InitialInstancesContainer const&) () from ./libGDCpp.so
#8  0x00007ffff735a2b7 in CppLayoutPreviewer::RefreshFromLayoutSecondPart() ()
   from ./libGDCpp.so
#9  0x00007ffff735ac25 in CppLayoutPreviewer::OnUpdate() () from ./libGDCpp.so
#10 0x00007ffff7a5b662 in gd::LayoutEditorCanvas::OnUpdate() ()
   from ./libGDCore.so
#11 0x00007ffff7a5f583 in gd::LayoutEditorCanvas::OnPaint(wxPaintEvent&) ()
   from ./libGDCore.so
#12 0x00007ffff5c608be in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const ()
---Type <return> to continue, or q <return> to quit---

```

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/48b5c8aa4296e1b2f3c942ee68a53fa22cfba671
It was related to the refactoring of ObjInstancesHolder where I forgot to clear objects inside the container (so old objects where living in memory and got destroyed at the wrong time). I've added tests for the class.
