### ISSUE TITLE
Crash with compiled game (only)

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#89]
With this project : http://forum.compilgames.net/viewtopic.php?p=48995#p48995
It crashes directly when I start the compiled game : 
```
Program received signal SIGSEGV, Segmentation fault.
0x66982356 in sf::operator==(sf::String const&, sf::String const&) ()
   from C:\Users\Victor\dynamic_structure_to_file\sfml-system-2.dll
(gdb) bt
#0  0x66982356 in sf::operator==(sf::String const&, sf::String const&) ()
   from C:\Users\Victor\dynamic_structure_to_file\sfml-system-2.dll
#1  0x669823d8 in sf::operator!=(sf::String const&, sf::String const&) ()
   from C:\Users\Victor\dynamic_structure_to_file\sfml-system-2.dll
#2  0x6b6219de in sf::Text::setString(sf::String const&) ()
   from C:\Users\Victor\dynamic_structure_to_file\sfml-graphics-2.dll
#3  0x6428b312 in ?? ()
   from C:\Users\Victor\dynamic_structure_to_file\Code.dll
#4  0x64284c05 in ?? ()
   from C:\Users\Victor\dynamic_structure_to_file\Code.dll
#5  0x64282852 in ?? ()
   from C:\Users\Victor\dynamic_structure_to_file\Code.dll
#6  0x64287f66 in ?? ()
   from C:\Users\Victor\dynamic_structure_to_file\Code.dll
#7  0x6943a828 in RuntimeScene::RenderAndStep() ()
   from C:\Users\Victor\dynamic_structure_to_file\GDCpp.dll
#8  0x0040465b in ?? ()
#9  0x004010db in ?? ()
#10 0x00401158 in ?? ()
#11 0x76c8338a in KERNEL32!BaseCleanupAppcompatCacheSupport ()
   from C:\Windows\syswow64\kernel32.dll
#12 0x0028ffd4 in ?? ()
#13 0x777a9f72 in ntdll!RtlpNtSetValueKey ()
   from C:\Windows\system32\ntdll.dll
#14 0x7efde000 in ?? ()
#15 0x777a9f45 in ntdll!RtlpNtSetValueKey ()
   from C:\Windows\system32\ntdll.dll
#16 0x00401140 in ?? ()
#17 0x00000000 in ?? ()
```

**Comment by victorlevasseur** [comment]
No, forget that bug, the Text extension wasn't activated in the project but Text objects were added to it.

**Comment by 4ian** [comment]
Still highlight the fact that GD should have a function to browse objects and events and automatically set used extensions. But good to know it's not a "real" bug ^^
